### ISSUE TITLE
Can't translate a page

### ISSUE THREAD

**Issue by higuita** [bpierre/gtranslate#18]
I may be missing something, but i cant translate a full page, i have no context menu without selection anything, and selecting the all page translate the text, not the page (like submitting a url to google translator )

IIRC, in the past i could translate the whole page and viewer it as a normal webpage.

**Comment by PerfectSlayer** [comment]
Hi @higuita 
I just push the feature (#37). Feel free to test and give you feedback! :+1:

**Comment by mote0230** [comment]
https://github.com/bpierre/gtranslate/commit/1140c694b95f72f391c8973e52ba554eeb374ead
Fixed, thanks PerfectSlayer

**Comment by PerfectSlayer** [comment]
You're welcome :wink:
