### ISSUE TITLE
"service unavailable" result of translation

### ISSUE THREAD

**Issue by xael-fry** [bpierre/gtranslate#23]
The addon stop working since some days, shows "service unavailable"

**Comment by bpierre** [comment]
Same here, it looks like Google really wants to close any remote access to Google Translate. Maybe it’s time to switch to Bing, as suggested in #4.

**Comment by xael-fry** [comment]
I manually call the url, and i get a Captcha, when filling it, I finally get the correct result.
I will try to have a deeper look.

**Comment by bpierre** [comment]
Yes same for me, and after some time, I need to fill the captcha again… I will have a look this week-end, I also have started a rewrite (not the API part though) to make it restartless and compatible with multiprocess tabs.

**Comment by rodolfobandeira** [comment]
Hi guys!
translate-shell fixed their problem. I believe if we verify their last commits we can found the solution to fix it to gTranslate.

https://github.com/soimort/translate-shell

**Comment by pautomas** [comment]
@bpierre woah! you're still mantaining it. Thanks a lot!

**Comment by bpierre** [comment]
@pautomas I am trying to! Thanks to you, I am still using it every day after all these years :pray:

**Comment by bpierre** [comment]
@rodolfobandeira Thanks, I will try to reproduce the request they are doing.

**Comment by pedro22** [comment]
Strange if I check a longer text, eg: "Hi guys!
translate-shell Their fixed the problem. I believe if the verify Their last commits we can found the solution to fix it is gTranslate" is gTranslate every time it works well, but I'll skip this the text "Hi guys!" It appears "service unavailable"

Regards.

**Comment by IGZrobertogonzalez** [comment]
Maybe this link can help: https://support.google.com/websearch/answer/86640?hl=en

**Comment by pedro22** [comment]
Captcha typed, but it does not help - beyond that as I wrote earlier gTranslate long sentences translators and short no.

**Comment by rodolfobandeira** [comment]
Nice shot @pedro22 ! Long sentences works.. the short ones or single words are failing.

**Comment by bpierre** [comment]
I started pushed a rewrite in this branch, using Jetpack (Addons SDK) instead of XUL (Legacy Extensions): https://github.com/bpierre/gtranslate/tree/jetpack

It’s not usable yet.

The basic features are working though, including the Google Translate request. I now have to implement the language selection, test a lot, and I will publish a release as soon as possible.

**Comment by elemoine** [comment]
Very cool @bpierre. Thanks for that!

**Comment by rodolfobandeira** [comment]
Hi @bpierre ! Thanks for the update! I just don't get it how to update my firefox extension with that one you created using Jetpack.

**Comment by bpierre** [comment]
Hi @rodolfobandeira, I will publish a .xpi as soon as it’s usable.

If you want to launch it yourself in the meantime, you have to install [jpm](https://github.com/mozilla/jpm), then run this in the addon directory:

```sh
$ make run
```

**Comment by achernyakevich** [comment]
I have slightly played with trying to translate different length phrases. It really looks that Google blocks almost everything that is short enough. I could detect that sentences longer than 139 symbols are translated without problems. :)

So I can suspect that Google just introduced restriction for their translation API usage trying to minimize number of calls for short phrases. Maybe we need to search for other API method for shorter sentences or find the way to assure Google that we are not spammers trying to overload its service.

**Comment by ahmadramadan** [comment]
I can't live without this plugin :(

**Comment by bpierre** [comment]
@achernyakevich Are you talking about the stable version, or the one from the [jetpack branch](https://github.com/bpierre/gtranslate/tree/jetpack)?

@ahmadramadan Same for me! I am very busy these days, but it’s on the top of my priority list. You can follow the progress here: https://github.com/bpierre/gtranslate/pull/24

**Comment by pedro22** [comment]
@bpierre Can create a firefox plugin to as beta, let people test and any errors will be reported.

**Comment by bpierre** [comment]
@pedro22 

Yes, I will drop a .xpi here as soon as possible, but for now it’s still too much broken and I need to fix these two points:

- The language menu is not finished
- The performances of the language menu generation are bad at the moment (if your computer is not fast enough, you have a delay before the context menu is displayed). I suspect the `context-menu` module from the Addons SDK, which is much slower than pure XUL, but I am trying to isolate the problem.

**Comment by anon0230** [comment]
Hi everyone, with the power of regexes I was able to fix the old version, mostly. Only thing still broken that I see is newlines and other stuff like that, it displays as \n.
You can download the xpi here: {aff87fa2-a58e-4edd-b852-0a20203c1e17}.xpi  http://a.pomf.se/agntdb.xpi

Or edit the file yourself, see http://pastebin.com/GRAYnVvj the translationRequest and getGoogleUrl

**Comment by achernyakevich** [comment]
@bpierre I checked for stable version 0.9 available from Mozilla Addons search.

**Comment by anon0230** [comment]
I spent some more time, fixed the issue with the newlines. Tried a lot to add new languages but couldn't get it to work. @bpierre feel free to use this as a temporary upgrade so people stop giving 2 star reviews.
http://a.pomf.se/gxfldu.xpi

**Comment by rodolfobandeira** [comment]
@anon0230 
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by bpierre** [comment]
@anon0230 Thanks for the update! Sadly it can’t be submitted to the Mozilla Addons without refactoring the code: the addon needs to be compatible with [E10s](https://wiki.mozilla.org/Electrolysis) (see #21), which is not the case for the current codebase.

Feel free to contribute to the `jetpack` branch though, the Google Translate module is in [providers/google-translate.js](https://github.com/bpierre/gtranslate/blob/jetpack/providers/google-translate.js), and it shouldn’t be too much work to add your improvements into it.

PS: In case you are not familiar with GitHub: you have to fork the project, make your modifications in your `jetpack` branch, then create a pull request from the `jetpack` branch of your repo into the `jetpack` branch of this repo.

**Comment by def00111** [comment]
You can use this function to get the selected text (works with e10s)

function getBrowserSelection(document) {
  const { BrowserUtils } = document.defaultView;
  
  let [element, focusedWindow] = BrowserUtils.getFocusSync(document);
  var selection = focusedWindow.getSelection().toString();
  // try getting a selected text in text input.
  if (!selection) {
    var isOnTextInput = function isOnTextInput(elem) {
      // we avoid to return a value if a selection is in password field.
      // ref. bug 565717
      return elem instanceof Ci.nsIDOMHTMLTextAreaElement ||
             (elem instanceof Ci.nsIDOMHTMLInputElement && elem.mozIsTextField(true));
    };

    if (isOnTextInput(element)) {
      selection = element.QueryInterface(Ci.nsIDOMNSEditableElement)
                         .editor.selection.toString();
    }
  }

  if (selection) {
    selection = selection.trim().replace(/\s+/g, " ");
  }
  return selection;
}

Note: You must pass a XULDocument to the fucnction.

**Comment by fedorvinogradov** [comment]
@mote0230 thanks a lot dude - works like a charm

**Comment by MarcoSchool** [comment]
Hope this solution gets updated into mozilla soon.
Great plugin by the way kudos.

**Comment by bpierre** [comment]
The release is almost ready, I just need to test it more.

Please try it and tell me if you see any issue: https://github.com/bpierre/gtranslate/releases/tag/v0.10

**Comment by def00111** [comment]
Working good :)
I also like the detected lang feature :)

**Comment by andrew-chiz-muzychuk** [comment]
Still not working.
I uninstall and install it - nothing.
Win 7 64, FF 37.0.2

**Comment by bpierre** [comment]
@andrew-chiz-muzychuk have you tried to install gtranslate.xpi from this page? https://github.com/bpierre/gtranslate/releases/tag/v0.10

**Comment by andrew-chiz-muzychuk** [comment]
@bpierre no, I didn't. I went to FF's Addons and install from there. And it was v 0.9. I've tried your link. It installed v 0.10, which works perfect.
Also, I like that this menu is at the very bottom. Very usfull.
Thanks a lot!

**Comment by bpierre** [comment]
Great!

> Also, I like that this menu is at the very bottom. Very useful.

I wasn’t sure about that… Maybe I should add an option to insert it at the top, at the bottom (as it is now), or just before the “Inspect Element”. I also need to add a separator.

**Comment by bpierre** [comment]
The update has been approved: https://addons.mozilla.org/firefox/addon/gtranslate/

**Comment by nemesis8185** [comment]
Hello @bpierre. The new version, 0.10.1, doesn't work with Menu Editor add-on. The old GTranslate version worked fine. Please, is it possible, in some way, that GTranslate works with Menu Editor 1.2.7? I love GTranslate, but uninstalling Menu Editor, makes a chaos of all my context menus. FOr now, I'm using the temporary GTranslate that was added to this page some days ago (the temporary solution). I would really love to be able to update to GTranslate 0.10.1, as it's a great (and irreplaceable) add-on.
Thanks for your time & for this great add-on!

**Comment by bpierre** [comment]
@nemesis8185 Hi, could you send me the page of the Menu Editor addon? I only find “Menu Editor II”, which is deprecated by the author. I answered here for the same issue https://github.com/bpierre/gtranslate/issues/28#issuecomment-99071855

**Comment by nemesis8185** [comment]
@bpierre, thanks for your answer! Menu Editor addon seems to be too old, and it has been removed from firefox addons page... This is the "official link" to the .xpi that appears on my Add-ons tab: http://menueditor.mozdev.org/ - There, you can find the .xpi That was the last version. Thanks a lot for taking time for this!!

**Comment by pedro22** [comment]
I updated the plugin to version 0.11.0 and I have no gTranslate item on the menu, and version 0.10.1 is - can you fix it?

Win XP SP3 - Firefox 38.0.1

**Comment by bpierre** [comment]
@pedro22 Could you open a new issue, and paste the results of `about:support` (Help => Troubleshooting Information)?

**Comment by pedro22** [comment]
@bpierre 

Dostrój Firefoksa
Tryb awaryjny
Informacje dla pomocy technicznej
Ta strona zawiera informacje techniczne, które mogą być przydatne podczas rozwiązywania problemów. Jeśli szukasz odpowiedzi na często zadawane pytania dotyczące programu Firefox, sprawdź naszą stronę wsparcia technicznego.
Informacje o aplikacji
Nazwa 	Firefox
Wersja 	38.0.1
ID kompilacji 	20150513174244
Historia aktualizacji 	
Kanał aktualizacji 	release
Identyfikator programu 	Mozilla/5.0 (Windows NT 5.1; rv:38.0) Gecko/20100101 Firefox/38.0
Folder profilu 	
Włączone wtyczki 	about:plugins
Konfiguracja kompilacji 	about:buildconfig
Zużycie pamięci 	about:memory
Okna wieloprocesowe 	0/1 (domyślnie: false)
Zgłoszenia awarii z ostatnich 3 dni
ID zgłoszenia 	Data przesłania

Wszystkie zgłoszenia awarii
Rozszerzenia
Nazwa 	Wersja 	Włączone 	ID
Adblock Plus	2.6.9	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Classic Theme Restorer (Customize UI)	1.3.2	true	ClassicThemeRestorer@ArisT2Noia4dev
gtranslate	0.10.1	true	{aff87fa2-a58e-4edd-b852-0a20203c1e17}
HttpFox	0.8.14	true	{4093c4de-454a-4329-8aff-c6b0b123c386}
Converter	1.2.3	false	{8B72860F-C5F8-4286-865E-D2C2DB98A9E6}
Edit Cookies	0.3.8.1	false	{ea2b95c2-9be8-48ed-bdd1-5fcd2ad0ff99}
Element Hiding Helper dla Adblock Plusa	1.3.2	false	elemhidehelper@adblockplus.org
Exif Viewer	2.00	false	exif_viewer@mozilla.doslash.org
Greasemonkey	3.1	false	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
ImageHost Grabber	1.6.6.20140620	false	{E4091D66-127C-11DB-903A-DE80D2EFDFE8}
ImTranslator	8.11	false	{9AA46F4F-4DC7-4c06-97AF-5035170634FE}
MEGA	2.0.221	false	firefox@mega.co.nz
Mozilla Archive Format	3.1.0	false	{7f57cf46-4467-4c2d-adfa-0cba7c507e54}
PhotoME Extension	2.1	false	{01c29d60-f7f0-416c-844a-ec8b2e1841d0}
UnMHT	7.3.0.5	false	{f759ca51-3a91-4dd1-ae78-9db5eee9ebf0}
Grafika
Data sterownika	10-22-2006
GPU #2 Active	false
ID dostawcy	0x10de
ID subsystemu	00000000
ID urządzenia	0x0185
Okna ze sprzętowym przyspieszeniem grafiki	0/1 Basic (OMTC) Zablokowane dla zainstalowanej wersji sterownika grafiki. Zalecana jest aktualizacja sterownika do wersji 257.21 lub nowszej.
Opis adaptera	NVIDIA GeForce4 MX 4000
RAM adaptera	Unknown
Renderer WebGL	Zablokowane dla zainstalowanej wersji sterownika grafiki. Zalecana jest aktualizacja sterownika do wersji 257.21 lub nowszej.
Sterowniki adaptera	nv4_disp
Wersja sterownika	6.14.10.9371
windowLayerManagerRemote	true
Włączone Direct2D	Zablokowane dla zainstalowanej wersji sterownika grafiki. Zalecana jest aktualizacja sterownika do wersji 257.21 lub nowszej.
Włączone DirectWrite	false (0.0.0.0)
AzureCanvasBackend	skia
AzureContentBackend	cairo
AzureFallbackCanvasBackend	cairo
AzureSkiaAccelerated	0
Ważne zmodyfikowane ustawienia
Nazwa 	Wartość accessibility.typeaheadfind.flashBar	0
browser.cache.disk.capacity	215040
browser.cache.disk.smart_size_cached_value	215040
browser.cache.disk.smart_size.first_run	false
browser.cache.disk.smart_size.use_old_max	false
browser.cache.frecency_experiment	2
browser.download.folderList	2
browser.download.importedFromSqlite	true
browser.download.manager.alertOnEXEOpen	true
browser.download.manager.showWhenStarting	false
browser.history_expire_days.mirror	180
browser.newtab.url	https://google.pl
browser.places.importBookmarksHTML	false
browser.places.importDefaults	false
browser.places.leftPaneFolderId	-1
browser.places.migratePostDataAnnotations	false
browser.places.smartBookmarksVersion	7
browser.places.updateRecentTagsUri	false
browser.privatebrowsing.autostart	true
browser.privatebrowsing.dont_prompt_on_enter	true
browser.search.useDBForOrder	true
browser.sessionstore.upgradeBackup.latestBuildID	20140923175406
browser.startup.homepage	https://google.pl
browser.startup.homepage_override.buildID	20150513174244
browser.startup.homepage_override.mstone	38.0.1
browser.tabs.animate	false
browser.tabs.closeButtons	0
browser.tabs.loadInBackground	false
browser.urlbar.formatting.enabled	false
browser.urlbar.trimURLs	false
dom.ipc.plugins.flash.disable-protected-mode	true
dom.mozApps.used	true
dom.w3c_touch_events.expose	false
extensions.lastAppVersion	38.0.1
font.internaluseonly.changed	true
general.autoScroll	false
gfx.blacklist.suggested-driver-version	257.21
gfx.content.azure.enabled	false
gfx.direct2d.disabled	true
image.animation_mode	none
javascript.options.showInConsole	false
media.gmp-gmpopenh264.enabled	false
media.gmp-gmpopenh264.lastUpdate	1431470441
media.gmp-gmpopenh264.version	1.4
media.gmp-manager.buildID	20150513174244
media.gmp-manager.lastCheck	1431867569
mousewheel.enable_pixel_scrolling	false
mousewheel.system_scroll_override_on_root_content.enabled	false
network.cookie.cookieBehavior	1
network.cookie.prefsMigrated	true
network.http.max-persistent-connections-per-server	10
network.http.pipelining	true
network.http.pipelining.maxrequests	8
network.http.proxy.pipelining	true
network.predictor.cleaned-up	true
places.database.lastMaintenance	1431823638
places.history.expiration.transient_current_max_pages	11311
places.history.expiration.transient_optimal_database_size	3549675
places.last_vacuum	1325853760
plugin.disable_full_page_plugin_for_types	
plugin.importedState	true
plugin.state.flash	0
plugin.state.np-mswmp	0
plugin.state.npdrmv	0
plugin.state.npdsplay	0
plugin.state.npgoogleupdate	0
plugin.state.npuploadplugin	0
plugin.state.npwmsdrm	0
plugin.state.npwpf	0
print.print_printer	Bullzip PDF Printer
print.printer_Bullzip_PDF_Printer.print_bgcolor	false
print.printer_Bullzip_PDF_Printer.print_bgimages	false
print.printer_Bullzip_PDF_Printer.print_command	
print.printer_Bullzip_PDF_Printer.print_downloadfonts	false
print.printer_Bullzip_PDF_Printer.print_edge_bottom	0
print.printer_Bullzip_PDF_Printer.print_edge_left	0
print.printer_Bullzip_PDF_Printer.print_edge_right	0
print.printer_Bullzip_PDF_Printer.print_edge_top	0
print.printer_Bullzip_PDF_Printer.print_evenpages	true
print.printer_Bullzip_PDF_Printer.print_footercenter	
print.printer_Bullzip_PDF_Printer.print_footerleft	&PT
print.printer_Bullzip_PDF_Printer.print_footerright	&D
print.printer_Bullzip_PDF_Printer.print_headercenter	
print.printer_Bullzip_PDF_Printer.print_headerleft	&T
print.printer_Bullzip_PDF_Printer.print_headerright	&U
print.printer_Bullzip_PDF_Printer.print_in_color	true
print.printer_Bullzip_PDF_Printer.print_margin_bottom	0.5
print.printer_Bullzip_PDF_Printer.print_margin_left	0.5
print.printer_Bullzip_PDF_Printer.print_margin_right	0.5
print.printer_Bullzip_PDF_Printer.print_margin_top	0.5
print.printer_Bullzip_PDF_Printer.print_oddpages	true
print.printer_Bullzip_PDF_Printer.print_orientation	0
print.printer_Bullzip_PDF_Printer.print_pagedelay	500
print.printer_Bullzip_PDF_Printer.print_paper_data	9
print.printer_Bullzip_PDF_Printer.print_paper_height	11,00
print.printer_Bullzip_PDF_Printer.print_paper_size_type	0
print.printer_Bullzip_PDF_Printer.print_paper_size_unit	1
print.printer_Bullzip_PDF_Printer.print_paper_width	8,50
print.printer_Bullzip_PDF_Printer.print_reversed	false
print.printer_Bullzip_PDF_Printer.print_scaling	1,00
print.printer_Bullzip_PDF_Printer.print_shrink_to_fit	true
print.printer_Bullzip_PDF_Printer.print_to_file	false
print.printer_Bullzip_PDF_Printer.print_unwriteable_margin_bottom	0
print.printer_Bullzip_PDF_Printer.print_unwriteable_margin_left	0
print.printer_Bullzip_PDF_Printer.print_unwriteable_margin_right	0
print.printer_Bullzip_PDF_Printer.print_unwriteable_margin_top	0
privacy.donottrackheader.enabled	true
privacy.popups.showBrowserMessage	false
privacy.sanitize.migrateFx3Prefs	true
security.disable_button.openCertManager	false
security.warn_viewing_mixed	false
storage.vacuum.last.index	1
storage.vacuum.last.places.sqlite	1430328706
Ważne zablokowane ustawienia
	Nazwa 	Wartość
JavaScript
Przyrostowy GC 	true
Ułatwienia dostępu
Aktywne 	false
Zablokuj ułatwienia dostępu 	0
Wersje bibliotek
	Oczekiwana wersja minimalna	Wersja w użyciu
NSPR	4.10.8	4.10.8
NSS	3.18.1 Basic ECC	3.18.1 Basic ECC
NSSSMIME	3.18.1 Basic ECC	3.18.1 Basic ECC
NSSSSL	3.18.1 Basic ECC	3.18.1 Basic ECC
NSSUTIL	3.18.1	3.18.1
Eksperymenty
Nazwa 	ID 	Opis 	Aktywny 	Data zakończenia 	Strona

**Comment by CatQuest** [comment]
hi, "service unavailable" is back. and this time no matter how much or little text is selected, it's the same; it's completely unworking now.

has google completely it down? :(

**Comment by IGZrobertogonzalez** [comment]
@CatQuest I think it was temporary. Now it's working

**Comment by farmazon3000** [comment]
new issue: https://github.com/bpierre/gtranslate/issues/43
