### ISSUE TITLE
Context menu only appears in first browser window

### ISSUE THREAD

**Issue by SuperGouge** [bpierre/gtranslate#28]
When opening multiple windows, the add-on only works in the first one. In the other ones, the context menu does not appear. I suspect this has to do with the use of the `getMostRecentBrowserWindow()` function.

**Comment by JonnyThree** [comment]
Hello i have a similar problem, so i decided to report it in this thread. The addon doesn't work with old "Menu editor" addon, there was no problems with old versions of gTranslate. And if i disable it, the context menu is in english: Translate ..... instead of Traduci ......, local language in my browser is italian.

**Comment by bpierre** [comment]
@SuperGouge Indeed, thanks! I will work on it.

@JonnyThree I think your problem may be related to restartless addons that do not use XUL overlays. Do you have the context menu icon with [uBlock](https://github.com/gorhill/uBlock) for example? Are you using [Menu Editor II](https://addons.mozilla.org/en-US/firefox/addon/menu-editor-ii/)? Have you removed the “Inspect” item by any chance?

**Comment by JonnyThree** [comment]
thanks for the answer. yes, i have ublock installed (how you know that?), and the icon of ublock is present. the "menu editor" addon is the same used by user nemesis8185, that have same problem in this thread, last comment: https://github.com/bpierre/gtranslate/issues/23

**Comment by mote0230** [comment]
I had a look into the menu editor extention, when you first install gtranslate, and translate something, and then go to menu editor it shows up there as "translate [text you selected]", and in the menu editor's save file. If you restart the browser it disappears. Compared to ublock, which shows up as blockElement in the save file. Looking in the source code: https://github.com/chrisaljoudi/uBlock/blob/master/src/js/contextmenu.js#L58

So my guess is that adding an 'id' to the contextmenu entry that isn't variable would solve it.

**Comment by bpierre** [comment]
Thanks, I will try that. I need to commit my changes for #26, I will check if it works with the Menu Editor extension.

**Comment by Andrefpvs** [comment]
Just to add to this, the issue also happens when opening a private browsing window (Firefox 27). I believe fixing the issue with new windows will also fix this, but it won't hurt to have private windows in mind when testing the fix :)
