### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by mote0230** [bpierre/gtranslate#29]
Pre-jetpack the addon was translated in a bunch of languages, I'll see how this can be done now.

**Comment by Klofutar** [comment]
Here's the Slovenian translation:

// Context Menu
const LABEL_LOADING = 'Pridobivanje prevoda …'
const LABEL_TRANSLATE = 'Prevedi “{0}”'
const LABEL_CHANGE_LANGUAGES = 'Spremeni jezika ({0} > {1})'

"description": "gtranslate je dodatek za Firefox, ki prevede izbrano besedilo z uporabo storitve Google Translate.",

console.log('Z dodatkom gtranslate lahko prevedete katerokoli besedilo na spletni strani tako, da ga izberete in kliknete na njega z desnim miškinim gumbom. Dodatek za prevajanje besedila uporablja storitev Google Translate.')
console.log()
console.log('gtranslate ni na noben način povezan s podjetjem Google Inc.')
console.log()
console.log('Značilnosti:')
console.log('<ul>')
console.log('<li>Prevede iz/v naslednje jezike: ' + langList + '.</li>')
console.log('<li>Samodejno zaznavanje jezika.</li>')
console.log('<li>Prevede lahko tudi opise slik in povezave.</li>')
console.log('</ul>')

**Comment by bpierre** [comment]
@Klofutar Thank you!
