### ISSUE TITLE
For single words, displaying other possible translations, and/or definitions

### ISSUE THREAD

**Issue by mote0230** [bpierre/gtranslate#33]
For some languages, google shows the definition and example usages. For example see https://translate.google.com/#en/en/home
These can get quite big, but can be added in the mouseover area.

For almost all(?) languages, google shows different possible translations, see
https://translate.google.com/#en/nl/home
These can be added to the mouseover area. For the 'match percentage', shown as grey bars, I'm not sure how to convert this to text compatible with the mouseover area, maybe some ascii art? Or just leave them out, or show the raw number?

When not translating to the same language, eg not from english to english, I would prioritize the different possible translations over the definition, as the definition is supposedly in a language that is not well known by the user, and when showing both, it would take a lot of screen space.

A setting should be provided so users can disable these features.

**Comment by PerfectSlayer** [comment]
Isn't the same as #16 ?

**Comment by mote0230** [comment]
yes it seems there is overlap

**Comment by z87** [comment]
Using this crude fix atm to show more translations:
`\resources\gtranslate\lib\providers\google-translate.js` at line 26
```javascript
  const translation = (
	result[1] ? result[1].map(chunk => chunk[0] + ': ' + chunk[1].join(', ')).join('; ') : 
    result[0] && result[0].map(chunk => chunk[0]).join(' ')
  ) || null
```
The result is like `noun: noun1, noun2; verb: verb1, verb2`

**Comment by mote0230** [comment]
https://github.com/bpierre/gtranslate/commit/6e5538e05457b919260ab1f3aa65b9c1ac42a289
For now alternative translations are implemented, but:
-should we show a sign in the non-mouseover text to show there is more in the mouseover?
-should we limit the amount of alternatives? How? The mouseover text can get quite large.

**Comment by bpierre** [comment]
@mote0230 I am just trying, that’s great!

>  -should we show a sign in the non-mouseover text to show there is more in the mouseover?

To indicate that we are in single word mode, maybe we could take the most popular one and display it directly in the menuitem:

```
maison (noun, synonims: maison, chambre, famille…)
```

>  -should we limit the amount of alternatives? How? The mouseover text can get quite large.
>  -The text column align didn't work as well as expected

Yes tooltips are really limited to format text, and highly depend on the OS. Maybe we could limit the alternatives to 10 or something like that, and each alternative to 10 words max.

**Comment by mote0230** [comment]
Looks like I'm not the only one who's "test word" is house ;)
For limiting to 10, map() doesn't support continue and break, so I think I would have to change it to use for loops, or do you know of a more functional style way to do this?

**Comment by bpierre** [comment]
You could use [`sort()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) to order the results, then [`slice()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort). You may have to associate the groups (noun, adjective) with each result before doing that, depending on how the data is structured. I am also OK with a for loop (you can use [for…of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) in Firefox).

> Looks like I'm not the only one who's "test word" is house ;)

Yes it’s from your example ;-)

**Comment by bpierre** [comment]
:cool: https://github.com/bpierre/gtranslate/releases/tag/v0.12.0
