### ISSUE TITLE
Open the new tab next to the current one

### ISSUE THREAD

**Issue by bpierre** [bpierre/gtranslate#34]
The new tab should open just on the right on the current tab, not at the end of the tabs bar.

The [`tabs.open()` method](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/tabs#open%28options%29) opens a tab at the end of the tabs bar by default.

- There is no option to do it in `tabs.open()`
- The `inBackground` option does the same, despite its description: “If present and true, the new tab will be opened **to the right of the active tab** and will not be active.” 
- Changing the tab position after opening it does not work: the move is visible to the user.

Some information here: https://bugzilla.mozilla.org/show_bug.cgi?id=715560

Need to investigate to find a solid solution.

**Comment by PerfectSlayer** [comment]
Hi @bpierre 

I tried to fix it but the inBackground option doesn't seem to open the tab at right of the active tab (as said in the documentation. Otherwise, a hack could be something like this:

```javascript
    // Open the translation page
    if (target === result) {
      tabs.open({
        url: translateUrl(currentFrom().code, currentTo().code, selection),
        inBackground: true,
        onOpen: function onOpen(tab) {
          tab.activate();
        }
      });
      return
    }
```

**Comment by bpierre** [comment]
Yes that’s what I tried first, but sadly the `inBackground` behaviour does not match with the documentation…

Another solution would be to manually change the position, but the tab jump is visible when using the `onOpen` callback.

**Comment by z87** [comment]
Is the callback necessary though? This works for me without any noticeable effects:
```javascript
const index = tabs.activeTab.index + 1
tabs.open(translateUrl(currentFrom(languages).code, currentTo(languages).code, selection))
tabs.activeTab.index = index
```

**Comment by bpierre** [comment]
@z87 Have you tried with and without E10S?

**Comment by z87** [comment]
@bpierre  Turns out it doesn't work with e10s at all. Sorry!

**Comment by def00111** [comment]
This should work just fine: 
```javascript
    // Open the translation page
    if (target === result) {
      let window = getMostRecentBrowserWindow()
      let url = translateUrl(currentFrom(languages).code, currentTo(languages).code, selection)
      window.gBrowser.loadOneTab(url, {relatedToCurrent: true})
      return
    }
```

Note: The pref "browser.tabs.insertRelatedAfterCurrent" must be true. (this pref is true by default)

Can you also add an option to make the tab active by default?
Like so:
```javascript
    // Open the translation page
    if (target === result) {
      let window = getMostRecentBrowserWindow()
      let url = translateUrl(currentFrom(languages).code, currentTo(languages).code, selection)
      window.gBrowser.loadOneTab(url, {relatedToCurrent: true, inBackground: option ? true : false})
      return
    }
```
Note: option is the pref. (gtranslate load in background setting)

**Comment by bpierre** [comment]
Thanks all!
