### ISSUE TITLE
There are no items on the menu gTranslate

### ISSUE THREAD

**Issue by pedro22** [bpierre/gtranslate#40]
I updated the plugin to version 0.11.0 and I have no gTranslate item on the menu, and version 0.10.1 is - can you fix it?

Win XP SP3 - Firefox 38.0.1

Informacje o aplikacji
----------------------

Nazwa: Firefox
Wersja: 38.0.1
ID kompilacji: 20150513174244
Kanał aktualizacji: release
Identyfikator programu: Mozilla/5.0 (Windows NT 5.1; rv:38.0) Gecko/20100101 Firefox/38.0
Okna wieloprocesowe: 0/1 (domyślnie: false)

Zgłoszenia awarii z ostatnich 3 dni
-----------------------------------

Wszystkie zgłoszenia awarii

Rozszerzenia
------------

Nazwa: Adblock Plus
Wersja: 2.6.9
Włączone: true
ID: {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}

Nazwa: Classic Theme Restorer (Customize UI)
Wersja: 1.3.2
Włączone: true
ID: ClassicThemeRestorer@ArisT2Noia4dev

Nazwa: gtranslate
Wersja: 0.10.1
Włączone: true
ID: {aff87fa2-a58e-4edd-b852-0a20203c1e17}

Nazwa: HttpFox
Wersja: 0.8.14
Włączone: true
ID: {4093c4de-454a-4329-8aff-c6b0b123c386}

Nazwa: Converter
Wersja: 1.2.3
Włączone: false
ID: {8B72860F-C5F8-4286-865E-D2C2DB98A9E6}

Nazwa: Edit Cookies
Wersja: 0.3.8.1
Włączone: false
ID: {ea2b95c2-9be8-48ed-bdd1-5fcd2ad0ff99}

Nazwa: Element Hiding Helper dla Adblock Plusa
Wersja: 1.3.2
Włączone: false
ID: elemhidehelper@adblockplus.org

Nazwa: Exif Viewer
Wersja: 2.00
Włączone: false
ID: exif_viewer@mozilla.doslash.org

Nazwa: Greasemonkey
Wersja: 3.1
Włączone: false
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

Nazwa: ImageHost Grabber
Wersja: 1.6.6.20140620
Włączone: false
ID: {E4091D66-127C-11DB-903A-DE80D2EFDFE8}

Nazwa: ImTranslator
Wersja: 8.11
Włączone: false
ID: {9AA46F4F-4DC7-4c06-97AF-5035170634FE}

Nazwa: MEGA
Wersja: 2.0.221
Włączone: false
ID: firefox@mega.co.nz

Nazwa: Mozilla Archive Format
Wersja: 3.1.0
Włączone: false
ID: {7f57cf46-4467-4c2d-adfa-0cba7c507e54}

Nazwa: PhotoME Extension
Wersja: 2.1
Włączone: false
ID: {01c29d60-f7f0-416c-844a-ec8b2e1841d0}

Nazwa: UnMHT
Wersja: 7.3.0.5
Włączone: false
ID: {f759ca51-3a91-4dd1-ae78-9db5eee9ebf0}

Grafika
-------

Data sterownika: 10-22-2006
GPU #2 Active: false
ID dostawcy: 0x10de
ID subsystemu: 00000000
ID urządzenia: 0x0185
Okna ze sprzętowym przyspieszeniem grafiki: 0/1 Basic (OMTC) Zablokowane dla zainstalowanej wersji sterownika grafiki. Zalecana jest aktualizacja sterownika do wersji 257.21 lub nowszej.
Opis adaptera: NVIDIA GeForce4 MX 4000
RAM adaptera: Unknown
Renderer WebGL: Zablokowane dla zainstalowanej wersji sterownika grafiki. Zalecana jest aktualizacja sterownika do wersji 257.21 lub nowszej.
Sterowniki adaptera: nv4_disp
Wersja sterownika: 6.14.10.9371
windowLayerManagerRemote: true
Włączone Direct2D: Zablokowane dla zainstalowanej wersji sterownika grafiki. Zalecana jest aktualizacja sterownika do wersji 257.21 lub nowszej.
Włączone DirectWrite: false (0.0.0.0)
AzureCanvasBackend: skia
AzureContentBackend: cairo
AzureFallbackCanvasBackend: cairo
AzureSkiaAccelerated: 0

Ważne zmodyfikowane ustawienia
------------------------------

accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.capacity: 215040
browser.cache.disk.smart_size_cached_value: 215040
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 2
browser.download.folderList: 2
browser.download.importedFromSqlite: true
browser.download.manager.alertOnEXEOpen: true
browser.download.manager.showWhenStarting: false
browser.history_expire_days.mirror: 180
browser.newtab.url: https://google.pl
browser.places.importBookmarksHTML: false
browser.places.importDefaults: false
browser.places.leftPaneFolderId: -1
browser.places.migratePostDataAnnotations: false
browser.places.smartBookmarksVersion: 7
browser.places.updateRecentTagsUri: false
browser.privatebrowsing.autostart: true
browser.privatebrowsing.dont_prompt_on_enter: true
browser.search.useDBForOrder: true
browser.sessionstore.upgradeBackup.latestBuildID: 20140923175406
browser.startup.homepage: https://google.pl
browser.startup.homepage_override.buildID: 20150513174244
browser.startup.homepage_override.mstone: 38.0.1
browser.tabs.animate: false
browser.tabs.closeButtons: 0
browser.tabs.loadInBackground: false
browser.urlbar.formatting.enabled: false
browser.urlbar.trimURLs: false
dom.ipc.plugins.flash.disable-protected-mode: true
dom.mozApps.used: true
dom.w3c_touch_events.expose: false
extensions.lastAppVersion: 38.0.1
font.internaluseonly.changed: true
general.autoScroll: false
gfx.blacklist.suggested-driver-version: 257.21
gfx.content.azure.enabled: false
gfx.direct2d.disabled: true
image.animation_mode: none
javascript.options.showInConsole: false
media.gmp-gmpopenh264.enabled: false
media.gmp-gmpopenh264.lastUpdate: 1431470441
media.gmp-gmpopenh264.version: 1.4
media.gmp-manager.buildID: 20150513174244
media.gmp-manager.lastCheck: 1431867569
mousewheel.enable_pixel_scrolling: false
mousewheel.system_scroll_override_on_root_content.enabled: false
network.cookie.cookieBehavior: 1
network.cookie.prefsMigrated: true
network.http.max-persistent-connections-per-server: 10
network.http.pipelining: true
network.http.pipelining.maxrequests: 8
network.http.proxy.pipelining: true
network.predictor.cleaned-up: true
places.database.lastMaintenance: 1431823638
places.history.expiration.transient_current_max_pages: 11311
places.history.expiration.transient_optimal_database_size: 3549675
places.last_vacuum: 1325853760
plugin.disable_full_page_plugin_for_types:
plugin.importedState: true
plugin.state.flash: 0
plugin.state.np-mswmp: 0
plugin.state.npdrmv: 0
plugin.state.npdsplay: 0
plugin.state.npgoogleupdate: 0
plugin.state.npuploadplugin: 0
plugin.state.npwmsdrm: 0
plugin.state.npwpf: 0
print.print_printer: Bullzip PDF Printer
print.printer_Bullzip_PDF_Printer.print_bgcolor: false
print.printer_Bullzip_PDF_Printer.print_bgimages: false
print.printer_Bullzip_PDF_Printer.print_command:
print.printer_Bullzip_PDF_Printer.print_downloadfonts: false
print.printer_Bullzip_PDF_Printer.print_edge_bottom: 0
print.printer_Bullzip_PDF_Printer.print_edge_left: 0
print.printer_Bullzip_PDF_Printer.print_edge_right: 0
print.printer_Bullzip_PDF_Printer.print_edge_top: 0
print.printer_Bullzip_PDF_Printer.print_evenpages: true
print.printer_Bullzip_PDF_Printer.print_footercenter:
print.printer_Bullzip_PDF_Printer.print_footerleft: &PT
print.printer_Bullzip_PDF_Printer.print_footerright: &D
print.printer_Bullzip_PDF_Printer.print_headercenter:
print.printer_Bullzip_PDF_Printer.print_headerleft: &T
print.printer_Bullzip_PDF_Printer.print_headerright: &U
print.printer_Bullzip_PDF_Printer.print_in_color: true
print.printer_Bullzip_PDF_Printer.print_margin_bottom: 0.5
print.printer_Bullzip_PDF_Printer.print_margin_left: 0.5
print.printer_Bullzip_PDF_Printer.print_margin_right: 0.5
print.printer_Bullzip_PDF_Printer.print_margin_top: 0.5
print.printer_Bullzip_PDF_Printer.print_oddpages: true
print.printer_Bullzip_PDF_Printer.print_orientation: 0
print.printer_Bullzip_PDF_Printer.print_pagedelay: 500
print.printer_Bullzip_PDF_Printer.print_paper_data: 9
print.printer_Bullzip_PDF_Printer.print_paper_height: 11,00
print.printer_Bullzip_PDF_Printer.print_paper_size_type: 0
print.printer_Bullzip_PDF_Printer.print_paper_size_unit: 1
print.printer_Bullzip_PDF_Printer.print_paper_width: 8,50
print.printer_Bullzip_PDF_Printer.print_reversed: false
print.printer_Bullzip_PDF_Printer.print_scaling: 1,00
print.printer_Bullzip_PDF_Printer.print_shrink_to_fit: true
print.printer_Bullzip_PDF_Printer.print_to_file: false
print.printer_Bullzip_PDF_Printer.print_unwriteable_margin_bottom: 0
print.printer_Bullzip_PDF_Printer.print_unwriteable_margin_left: 0
print.printer_Bullzip_PDF_Printer.print_unwriteable_margin_right: 0
print.printer_Bullzip_PDF_Printer.print_unwriteable_margin_top: 0
privacy.donottrackheader.enabled: true
privacy.popups.showBrowserMessage: false
privacy.sanitize.migrateFx3Prefs: true
security.disable_button.openCertManager: false
security.warn_viewing_mixed: false
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1430328706

Ważne zablokowane ustawienia
----------------------------

JavaScript
----------

Przyrostowy GC: true

Ułatwienia dostępu
------------------

Aktywne: false
Zablokuj ułatwienia dostępu: 0

Wersje bibliotek
----------------

NSPR
Oczekiwana wersja minimalna: 4.10.8
Wersja w użyciu: 4.10.8

NSS
Oczekiwana wersja minimalna: 3.18.1 Basic ECC
Wersja w użyciu: 3.18.1 Basic ECC

NSSSMIME
Oczekiwana wersja minimalna: 3.18.1 Basic ECC
Wersja w użyciu: 3.18.1 Basic ECC

NSSSSL
Oczekiwana wersja minimalna: 3.18.1 Basic ECC
Wersja w użyciu: 3.18.1 Basic ECC

NSSUTIL
Oczekiwana wersja minimalna: 3.18.1
Wersja w użyciu: 3.18.1

Eksperymenty
------------

**Comment by pedro22** [comment]
I downloaded Firefox Portable 38.0.1 and gTransate version 0.11.0 works, so it must be something with the settings in the installation version - can have an impact that I'm using Private mode?

Application Basics
------------------

Name: Firefox
Version: 38.0.1
Build ID: 20150513174244
Update Channel: release
User Agent: Mozilla/5.0 (Windows NT 5.1; rv:38.0) Gecko/20100101 Firefox/38.0
Multiprocess Windows: 0/1 (default: false)

Crash Reports for the Last 3 Days
---------------------------------

All Crash Reports

Extensions
----------

Name: gtranslate
Version: 0.11.0
Enabled: true
ID: {aff87fa2-a58e-4edd-b852-0a20203c1e17}

Graphics
--------

Adapter Description: NVIDIA GeForce4 MX 4000
Adapter Drivers: nv4_disp
Adapter RAM: Unknown
Device ID: 0x0185
Direct2D Enabled: Blocked for your graphics driver version. Try updating your graphics driver to version 182.65 or newer.
DirectWrite Enabled: false (0.0.0.0)
Driver Date: 10-22-2006
Driver Version: 6.14.10.9371
GPU #2 Active: false
GPU Accelerated Windows: 0/1 Basic (OMTC) Blocked for your graphics driver version. Try updating your graphics driver to version 182.65 or newer.
Subsys ID: 00000000
Vendor ID: 0x10de
WebGL Renderer: Blocked for your graphics driver version. Try updating your graphics driver to version 182.65 or newer.
windowLayerManagerRemote: true
AzureCanvasBackend: skia
AzureContentBackend: cairo
AzureFallbackCanvasBackend: cairo
AzureSkiaAccelerated: 0

Important Modified Preferences
------------------------------

browser.cache.disk.capacity: 0
browser.cache.disk.smart_size.enabled: false
browser.cache.disk.smart_size.first_run: false
browser.cache.frecency_experiment: 3
browser.download.importedFromSqlite: true
browser.download.useDownloadDir: false
browser.places.importBookmarksHTML: false
browser.places.smartBookmarksVersion: 7
browser.startup.homepage_override.buildID: 20150513174244
browser.startup.homepage_override.mstone: 38.0.1
extensions.lastAppVersion: 38.0.1
media.gmp-gmpopenh264.lastUpdate: 1432681041
media.gmp-gmpopenh264.version: 1.4
media.gmp-manager.buildID: 20150513174244
media.gmp-manager.lastCheck: 1432681040
network.cookie.prefsMigrated: true
network.predictor.cleaned-up: true
places.database.lastMaintenance: 1432681127
places.history.expiration.transient_current_max_pages: 10346
plugin.disable_full_page_plugin_for_types: application/pdf
privacy.sanitize.migrateFx3Prefs: true

Important Locked Preferences
----------------------------

JavaScript
----------

Incremental GC: true

Accessibility
-------------

Activated: false
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.10.8
Version in use: 4.10.8

NSS
Expected minimum version: 3.18.1 Basic ECC
Version in use: 3.18.1 Basic ECC

NSSSMIME
Expected minimum version: 3.18.1 Basic ECC
Version in use: 3.18.1 Basic ECC

NSSSSL
Expected minimum version: 3.18.1 Basic ECC
Version in use: 3.18.1 Basic ECC

NSSUTIL
Expected minimum version: 3.18.1
Version in use: 3.18.1

Experimental Features
---------------------

**Comment by bpierre** [comment]
> can have an impact that I'm using Private mode?

Indeed, closing this since we already have the issue #38 for that.
