### ISSUE TITLE
unsafe CPOW usage

### ISSUE THREAD

**Issue by def00111** [bpierre/gtranslate#41]
Your add-on spams alot "unsafe CPOW usage" warnings in the error/web console.
I have looked in the source and i suggest you change
```javascript
const getSelectionFromWin = win => {
  const popupNode = win.gContextMenuContentData.popupNode
  return (popupNode && getSelectionFromNode(popupNode)) || ''
}
```
to
```javascript
const getSelectionFromWin = win => {
  return win.gContextMenu.linkTextStr || win.gContextMenu.textSelected || ''
}
```
then the warnings will disappear.

For the "unsafe CPOW usage" warnings:
http://blog.lassey.us/2015/01/10/unsafe-cpow-usage/

Because now, your add-on isn't compatible with e10s.

But the problem is "win.gContextMenu.textSelected" returns not the whole selected text (only 150 chars max).
Source: https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/BrowserUtils.jsm#322

**Comment by def00111** [comment]
unsafe CPOW usage fix https://github.com/bpierre/gtranslate/pull/42

**Comment by mote0230** [comment]
I see you did some work on this here https://github.com/def00111/gtranslate/commit/40b1000d1906afcabf2c7baea7bcc8b8ef5fe4d8
Does it work, and do you think it (or parts of it) can be merged back?

**Comment by mote0230** [comment]
Fixed in https://github.com/bpierre/gtranslate/commit/a7c7613a3c1cf298dab6ecaac29dc41ab537a6c8
Thanks a lot @def00111
