### ISSUE TITLE
gtranslate not working (right click on text selection)

### ISSUE THREAD

**Issue by ctrl8511** [bpierre/gtranslate#47]
hello, 
I have a problem with gtranslate, time ago it simply stop working. 
If I select any text on any web page and then right click, well, gtranslate do not appears as usual...
why?

I also tried to uninstall completely firefox but the problem is still present, with a "fresh" firefox just installed

I am searching for a solution..

**Comment by PerfectSlayer** [comment]
Hi @ctrl8511 

Did you try to check the browser console about the extension? May be there is some errors or logs which could help.
The easiest way to do it is to go to add-ons and select « debug » button on gTranslate extension row.
Accept the popup and a console window will open. Then use the extension and watch the console to check possible errors.

Good luck!

P.S. : When you tried with a fresh Firefox install, did you keep your profile?

**Comment by ctrl8511** [comment]
hi, when I reinstall a sw I never keep profile or what, so can be a real fresh sw install, I was meaning completely fresh. 
but there is another strange thing :\
in the add-ons list, gtranslate extension, the "debug " button can't be pressed, see: http://s1.postimg.org/i7tfbsb9n/zdfgdfg.png 
it's curious that the "debug" button is present (but not press-able) with a non-standard firefox appearance (actually I'm on another pc with same gtranslate problem and I am using Lavafox v2 and the debug button correctly appears)
with the standard firefox appearance ("the default theme") strangely the debug button do not appears, do not know why... only "disable" and "remove" buttons available if I do not install (and in use) another FF theme. 
argh, what's happening? it's just me or what.

**Comment by bpierre** [comment]
I can’t reproduce it, but a new version has been published and may fix your issue: https://addons.mozilla.org/en-US/firefox/addon/gtranslate/versions/?page=1#version-0.12.0

Please reopen if the problem persists.
