### ISSUE TITLE
Add support for ES6 / Firefox 44

### ISSUE THREAD

**Issue by PerfectSlayer** [bpierre/gtranslate#54]
Firefox 44 brings Ecmascript 6 support and include some breaking changes.
For more details, check [the blog post about this topic](https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/).

The extension is affected (for example, no more translation due to code like:
```
// Context Menu
const LABEL_LOADING = 'Fetching translation…'
const LABEL_TRANSLATE = 'Translate “{0}”'
const LABEL_TRANSLATE_PAGE = 'Translate Page ({0} > {1})'
const LABEL_CHANGE_LANGUAGES = 'Change Languages ({0} > {1})'
```

This issue is a tracking issue for the Firefox 44 support.

**Comment by bpierre** [comment]
The issue with the `format()` function should be fixed since that commit: https://github.com/bpierre/gtranslate/commit/9f17b44dffff3981faa78749a77c70a31bb06939

Is this the issue you are talking about?

**Comment by PerfectSlayer** [comment]
My bad... It seems I stay on one of my outdated feature branches. Seems to work fine with Firefox 44 :wink:

**Comment by bpierre** [comment]
:+1:
