### ISSUE TITLE
Move 2MB of graphics from addon to AMO

### ISSUE THREAD

**Issue by spideymouse** [bpierre/gtranslate#55]
The latest Version 0.12.0 has gtranslate inherently contain the graphics within its code, turning a 22kB add-on into a 2MB one. I suggest that you upload the screenshots directly onto AMO and remove the graphics from the add-on, keeping it lightweight.

**Comment by PerfectSlayer** [comment]
Hi @spideymouse 

Good idea! I will setup an ignore list for SDK pacakaging to not include screenshots in xpi.
Thanks.
