### ISSUE TITLE
Google Translate Service Error

### ISSUE THREAD

**Issue by bpierre** [bpierre/gtranslate#57]
The Google Translate service is not responding properly, looks like they changed something again…

**Comment by farmazon3000** [comment]
same here

**Comment by mote0230** [comment]
They changed their token.  Just have to clean up the code a little now and I'll commit a fix.

**Comment by mote0230** [comment]
I created a pull request.

**Comment by bpierre** [comment]
The fix is published and awaiting review. Thanks again @mote0230, it works fine for me now.

https://addons.mozilla.org/en-US/firefox/addon/gtranslate/versions/?page=1#version-0.13.0
https://github.com/bpierre/gtranslate/releases/tag/v0.13.0
