### ISSUE TITLE
Move to paid Google Translate API

### ISSUE THREAD

**Issue by farmazon3000** [bpierre/gtranslate#71]
Did you consider moving to paid Google Translate API to avoid problems like #69? You may think about releasing paid version or crowd funding?

**Comment by bpierre** [comment]
gtranslate is fully open source and we can not include a secret key without breaking this principle. The only way would be to add some fields in the settings to allow people to do it themselves.

I don’t think it would work, as it is clearly targeting developers, and the experience of having to manage a Google Translate API account would be awful for someone who just want to use an addon that provides translation.

It is a very frustrating situation, and I hope Google will reconsider its position for open source projects in the future…

**Comment by farmazon3000** [comment]
Fair enough.
