### ISSUE TITLE
Google Translate Service Error

### ISSUE THREAD

**Issue by SemenMartynov** [bpierre/gtranslate#72]
#### What steps will reproduce the problem?
1. Common usage: select text and choose translate in context menu

#### What is the expected behavior? What do you see instead?
Translate))

#### Could you describe us your platform?
* Firefox version: 46.0
* Operating system: Ubuntu Xenial Xerus

#### Anything else to add to help us?
It looks like many user have faced this problem -- https://addons.mozilla.org/en-US/firefox/addon/gtranslate/

**Comment by bpierre** [comment]
Are you using the latest version? This problem should be fixed since the version 0.13.1.

**Comment by SemenMartynov** [comment]
Oh, it looks like my firefox hasn't managed to download update.
Now everything works well. Thank you for your work!
