### ISSUE TITLE
gtranslate doesn't translate word

### ISSUE THREAD

**Issue by wasmachien** [bpierre/gtranslate#8]
Hi,

Since a couple of weeks gtranslate stopped working. Instead of translating the word it just shows the original. It's set to automatically recognize the language and translate it to English. Here's a screenshot:

![](http://i.imgur.com/jPyBs.jpg)

I'm running the Russian localization of Firefox 8.0.1.

Thanks

**Comment by bpierre** [comment]
Closing this issue because the addon has been rewritten from scratch.
