### ISSUE TITLE
Check Firefox e10s compability

### ISSUE THREAD

**Issue by SemenMartynov** [bpierre/gtranslate#81]
Hi! Can you check and confirm, that gtranslate is fully compatible with Firefox Electrolysis?
On `http://arewee10syet.com/` there is status `unknown` near the gtranslate.

**Comment by SemenMartynov** [comment]
When gtranslate enabled, my system (Arch Linux && FF49.0) shows `Multiprocess Windows: 0/1 (Disabled by add-ons)`, but when I disable it,  multiprocess stats to work...

**Comment by S3ndG** [comment]
With FF 49, only a few while-listed add-ons work with e10s. If you want to use gtranslate with e10sand ff 49, you can force e10s : https://wiki.mozilla.org/Electrolysis#Force_Enable
or you can wait for future release of firefox :)

**Comment by SemenMartynov** [comment]
So, there is no need to aspire to get into this list?

**Comment by S3ndG** [comment]
Please read this part of the wiki : https://wiki.mozilla.org/Electrolysis#Add-ons_Schedule

**Comment by SemenMartynov** [comment]
OK, thank you!

**Comment by PerfectSlayer** [comment]
I reopened the issue as its remark is good.
As you can see, [the addon description](https://github.com/bpierre/gtranslate/blob/master/package.json#L24) does not provide information about e10s compatibility.

If the addon supports it, it should request the following permission:
```
multiprocess: true
```
as documented [here](https://developer.mozilla.org/fr/Add-ons/SDK/Tools/package_json#permissions).
We need to test it, then mark it if supported. Otherwise, we need to upgrade it for e10s support.

Thanks @SemenMartynov

**Comment by PerfectSlayer** [comment]
I confirm the addon is not electrolysis compatible for now.

Here is a preview when addon is now running in compatibility mode:
![gtranslate-e10s](https://cloud.githubusercontent.com/assets/1766222/18813481/df75eca2-82fb-11e6-94ed-cdce0b791c26.png)
As you can see, it's broken… 😞

**Comment by S3ndG** [comment]
On my computer, with FF 49.0.1 and e10s enabled, gtranslate works well. The only problem I have with it is a more longer start-up of firefox...

**Comment by PerfectSlayer** [comment]
@S3ndG If an addon doesn't declare it is compatible with e10s, it will work in a compatibility mode.
So it won't be blocked at startup and keeps working as expected but with poor performance.

**Comment by S3ndG** [comment]
Hello,
how do you declare that gtranslate is compatible with e10s?  It would be great if it doesn't work in a compatibility mode, for better performance :)

**Comment by PerfectSlayer** [comment]
Hi @S3ndG
Look at the link I post when I reopen the issue about addon description. All documentation is here :wink:

**Comment by S3ndG** [comment]
Hi :)
It would be great if gtranslate would be marked compatible with e10s for the release of FF 50, I could have multi-process enabled by default : https://wiki.mozilla.org/Electrolysis#Add-ons_Schedule
All the webextensions should work with FF 50 too.

**Comment by S3ndG** [comment]
Hello,
I have opened package.json with notepad and I notice this : 
**"permissions": { "private-browsing": true },**

Could you tell me how can I add "multiprocess": true  to the permissions?
thanks :)

**Comment by bpierre** [comment]
@PerfectSlayer It works for me with the shim disabled. Maybe something else has changed since when you tried it?

Closing for now https://github.com/bpierre/gtranslate/commit/91f0e265a5f489af4fb28770c9d5adb071ec338c
