### ISSUE TITLE
Doesn't work with FF57 Quantum

### ISSUE THREAD

**Issue by Scaurus** [bpierre/gtranslate#82]
Doesn't work with FF57 Quantum

#### Could you describe us your platform?
* Firefox version:  FF57 Quantum
* Operating system: MacOS 10.12.6

**Comment by PerfectSlayer** [comment]
Hi @Scaurus.
It looks like the same issue as #66.

**Comment by cezar-carneiro** [comment]
It would be great if it could work on quantum

**Comment by bpierre** [comment]
I am closing this issue, as we already have #66.
