### ISSUE TITLE
auto language detect not working

### ISSUE THREAD

**Issue by mattdarwin** [bpierre/gtranslate#9]
I use this plugin all the time to translate from 4 languages to English.  But it seems the auto language detect feature isn't working for me.

See screenshot here:
https://docs.google.com/open?id=0B8oIc_TxbpZncks5SFVCN1pGNEE

What could be going wrong?

I switched on the javascript debug, but the error console shows nothing.

If I switch the language from 'auto-detect' to 'French' it works fine. 

I tried using firebug to debug the ajax but it's not showing up.

**Comment by bpierre** [comment]
Closing this issue because the addon has been rewritten from scratch.
